### ISSUE TITLE
Release 0.4.0 breaks memcached functionality 

### ISSUE THREAD

**Issue by rekup** [cortexproject/cortex-helm-chart#135]
Installing / upgrading cortex to chart `v0.4.0` seems to break the memcached functionality (memcached gets uninstalled which causes cortex to fail if I upgrade to `v0.4.0`) . Somehow the memcached dependencies are not installed even when declaring `tags.blocks-storage-memcached=true`. To verify this, I ran the following command (I know that more configuration options need to be present to properly configure cortex for block storage, but this command should be sufficient to reproduce the issue):

```bash
helm install --dependency-update --verify=false --dry-run cortex --namespace cortex --set tags.blocks-storage-memcached=true cortex-helm/cortex | grep -i memcached
```

When I pull the chart, update the dependencies and then install it from the local folder everything seems to work:

```bash
helm pull cortex-helm/cortex
tar xzf cortex-0.4.0.tgz
helm dep update cortex/
helm install --dependency-update --verify=false --dry-run cortex --namespace cortex --set tags.blocks-storage-memcached=true cortex/ | grep -i memcached
```

Looks like the dependencies in the `v0.4.0` release are missing somehow.

**Comment by rekup** [comment]
I guess this issue could be fixed by creating a new release `v0.4.1` and make sure to run `helm dependency update` beforehand or use the `--dependency-update ` flag during the `helm package` command

**Comment by gburton1** [comment]
@khaines it does appear that the `charts/` folder was not regenerated when you packaged 0.4.0. Could you cut 0.4.1 after packaging it with the `--dependency-update`?

`helm package --dependency-update`

If you look at the cortex-0.4.0.tgz artifact, the charts/memcached/Chart.yaml shows the same content as cortex-0.3.0.tgz. 
```
apiVersion: v1
appVersion: 1.5.20
description: Free & open source, high-performance, distributed memory object caching
  system.
home: http://memcached.org/
icon: https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Memcached.svg/1024px-Memcached.svg.png
keywords:
- memcached
- cache
maintainers:
- email: gtaylor@gc-taylor.com
  name: gtaylor
- email: o.with@sportradar.com
  name: olemarkus
- email: k.aasan@sportradar.com
  name: kennethaasan
name: memcached
sources:
- https://github.com/docker-library/memcached
version: 3.2.3
```

But it should show the newer Bitnami chart:
```
annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.6.9
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Chart for Memcached
home: https://github.com/bitnami/charts/tree/master/bitnami/memcached
icon: https://bitnami.com/assets/stacks/memcached/img/memcached-stack-220x234.png
keywords:
- memcached
- cache
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: memcached
sources:
- https://github.com/bitnami/bitnami-docker-memcached
- http://memcached.org/
version: 5.5.1
```
