### ISSUE TITLE
query frontend prometheus endpoint?

### ISSUE THREAD

**Issue by justinrush** [cortexproject/cortex-helm-chart#222]
I deployed the chart with the below values and it seems to be ingesting data fine, but I can't seem to figure out the endpoint to use for grafana to access the prometheus api of cortex. It doesn't seem to be any of these:
* curl http://cortex-query-frontend.cortex.svc.cluster.local:8080/api/prom/prometheus
* curl http://cortex-query-frontend.cortex.svc.cluster.local:8080/prom
* curl http://cortex-query-frontend.cortex.svc.cluster.local:8080/prometheus

A nice enhancement to the README, or a guide, etc, would be to add examples of how to get the block storage working. Also just some general, "now that you've deployed, these are the default endpoints and paths that exist".

as an aside, it didn't seem to create the ingress record... but thats something for later as i'm just accessing in cluster for the moment.

```yaml
nginx:
  enabled: false
ingress:
  enabled: true
  hosts:
    - host: my-external-host
      path:
        - /cortex
  tls:
    - hosts:
      - my-external-host
config:
  api:
    prometheus_http_prefix: /prometheus
  auth_enabled: false
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: etcd
          # https://cortexmetrics.io/docs/configuration/configuration-file/#etcd_config
          etcd:
            endpoints:
              - cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local:2379
              - cortex-etcd-1.cortex-etcd-headless.cortex.svc.cluster.local:2379
              - cortex-etcd-2.cortex-etcd-headless.cortex.svc.cluster.local:2379
  storage:
    engine: blocks
  # https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config
  blocks_storage:
    backend: azure
    tsdb:
      dir: /data/tsdb
    bucket_store:
      sync_dir: /data/tsdb-sync
    azure:
      container_name: cortex
      account_name: my-name
      account_key: my-key
  querier:
    # Used when the blocks sharding is disabled.
    store_gateway_addresses: "cortex-store-gateway-headless:9095"
  # https://cortexmetrics.io/docs/configuration/configuration-file/#query_frontend_config
  frontend:
    
memcached:
  enabled: true
memcached-index-read:
  enabled: true
memcached-index-write:
  enabled: true
memcached-frontend:
  enabled: true
```

**Comment by ShuzZzle** [comment]
> I deployed the chart with the below values and it seems to be ingesting data fine, but I can't seem to figure out the endpoint to use for grafana to access the prometheus api of cortex. It doesn't seem to be any of these:

Should be: http://cortex-query-frontend.cortex.svc.cluster.local:8080/api/prom

> as an aside, it didn't seem to create the ingress record... but thats something for later as i'm just accessing in cluster for the moment.

That is because nginx needs to be enabled in order for this work, funny enough

**Comment by justinrush** [comment]
api/prom isn't working for me - the config file that is running on the query front-end is below:
```
$ curl http://cortex-query-frontend.cortex.svc.cluster.local:8080/api/prom
404 page not found
```

I do see these messages in the pod logs (4 of them), but they happened right when pod start up and the /ready endpoint returns ready, so I'm assuming they were just init related.

```
level=info ts=2021-09-14T13:49:38.57765804Z caller=frontend.go:351 msg="not ready: number of queriers connected to query-frontend is 0" 
```

Sure, happy to look at the wiki and drop some configs in.

For nginx - i can't use an existing nginx ingress controller?

```yaml
alertmanager:
  external_url: /api/prom/alertmanager
api:
  prometheus_http_prefix: /prometheus
  response_compression_enabled: true
auth_enabled: false
blocks_storage:
  azure:
    account_key: my-key
    account_name: my-account
    container_name: cortex
  backend: azure
  bucket_store:
    sync_dir: /data/tsdb-sync
  tsdb:
    dir: /data/tsdb
chunk_store:
  chunk_cache_config:
    memcached:
      expiration: 1h
    memcached_client:
      timeout: 1s
distributor:
  pool:
    health_check_ingesters: true
  shard_by_all_labels: true
frontend:
  log_queries_longer_than: 10s
ingester:
  lifecycler:
    final_sleep: 0s
    join_after: 0s
    num_tokens: 512
    ring:
      kvstore:
        consul:
          consistent_reads: true
          host: consul:8500
          http_client_timeout: 20s
        etcd:
          endpoints:
          - cortex-etcd-0.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-1.cortex-etcd-headless.cortex.svc.cluster.local:2379
          - cortex-etcd-2.cortex-etcd-headless.cortex.svc.cluster.local:2379
        prefix: collectors/
        store: etcd
      replication_factor: 3
  max_transfer_retries: 0
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
limits:
  enforce_metric_name: false
  max_query_lookback: 0s
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  bind_port: 7946
  join_members: []
querier:
  active_query_tracker_dir: /data/cortex/querier
  query_ingesters_within: 12h
  store_gateway_addresses: cortex-store-gateway-headless:9095
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      memcached:
        expiration: 1h
      memcached_client:
        timeout: 1s
  split_queries_by_interval: 24h
ruler:
  enable_alertmanager_discovery: false
schema:
  configs:
  - chunks:
      period: 168h
      prefix: chunks_
    from: "2020-11-01"
    index:
      period: 168h
      prefix: index_
    object_store: cassandra
    schema: v10
    store: cassandra
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 8080
storage:
  azure:
    account_key: null
    account_name: null
    container_name: null
  cassandra:
    addresses: null
    auth: true
    keyspace: cortex
    password: null
    username: null
  engine: blocks
  index_queries_cache_config:
    memcached:
      expiration: 1h
    memcached_client:
      timeout: 1s
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```
