### ISSUE TITLE
ruler-dep error after upgrading to 1.0.0

### ISSUE THREAD

**Issue by mvkrishna86** [cortexproject/cortex-helm-chart#269]
Hi,

I am getting the below error after upgrading my helm release to 1.0.0 from 0.7.0.
```
Helm upgrade failed: YAML parse error on cortex/templates/ruler/ruler-dep.yaml: error converting YAML to JSON: yaml: line 136: did not find expected key
```

I am using Kustomization with flux, so flux is directly pulling the charts from cortexproject repo. Till yesterday its working fine. after updating the tag to 1.11.0, it started giving this error. My helm controller just giving me this error and no other info. Can some one help me?

Below is the ruler config I am using in values.yaml:

```
    ruler:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: 1800m
          memory: 12Gi
        requests:
          cpu: 900m
          memory: 8Gi
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      serviceMonitor:
        enabled: true
        additionalLabels:
          app: cortex-ruler
          release: kube-prometheus-stack
      extraVolumes:
        - name: rules
          emptyDir: {}
      extraVolumeMounts:
        - mountPath: /etc/cortex/rules
          name: rules
      sidecar:
        enabled: true
        label: cortex_rules
        labelValue: "true"
        folder: /data/rules
        folderAnnotation: orgid
      ruler:
        alertmanager_url: http://cortex-alertmanager.monitoring.svc.cluster.local/api/prom/alertmanager
        enable_alertmanager_discovery: false
        enable_alertmanager_v2: false
        enable_api: true
        enable_sharding: true
        rule_path: /etc/cortex/rules
        ring:
          kvstore:
            store: memberlist
      ruler_storage:
        backend: local
        local:
          directory: /data/rules
        s3:
          bucket_name: tfnsl-cortex-ruler-ap-south-1
          endpoint: s3.dualstack.ap-south-1.amazonaws.com
          region: ap-south-1
          sse:
            type: SSE-S3

```
