### ISSUE TITLE
need guidance on how to add alertmanager config using helm values

### ISSUE THREAD

**Issue by ahsan-n** [cortexproject/cortex-helm-chart#283]
So I get multiple docs related how to setup alert manager in detail but they are either using `cortextool` or `POST` method. Like [this one](https://cortexmetrics.io/docs/api/#set-alertmanager-configuration). 
We are trying to achieve this by using helm chart values. But unsure where we can add alertmanager config template like we can do in prometheus:
```
alertmanagerFiles:
  alertmanager.yml:
    global:
    route:
      group_by: [alertname]
      group_wait: 10s
      repeat_interval: 3h
      receiver: 'slack-notifications'
```
will really be thankful for any help I can get :)
