### ISSUE TITLE
Memberlist doesn't work out of box

### ISSUE THREAD

**Issue by jiachengxu** [cortexproject/cortex-helm-chart#289]
I can see that from cortex chart v1.0.0, we use memberlist for kv store by default. However, I encounter the following errors in logs with memberlist configured:

```
Suspect cortex-ingester-1-80eee0bd has failed, no acks received
Refuting a suspect message (from: cortex-querier-5f4b9746c9-rc2z7-78c6210a)
Was able to connect to cortex-ruler-5d95b76f44-gx54v-8679e2d8 but other probes failed, network may be misconfigured
```

The above(similar) logs actually appear in all components which are using memberlist.

I have tried to investigate this issue, and I found something related to this: https://github.com/hashicorp/consul/issues/3058

Looks like we need to open some extra ports for probes? Or did I understand issue correctly?

**Comment by ShuzZzle** [comment]
Looks to be more like a configuration error. Have you made sure that you installed the chart with helm upgrade <releaseName> <name> `--reset-values`? Otherwise helm will keep previous values

**Comment by jiachengxu** [comment]
@ShuzZzle Thanks for your reply, I actually deployed cortex from start, and I don't really think there were any previous values.

**Comment by ShuzZzle** [comment]
> @ShuzZzle Thanks for your reply, I actually deployed cortex from start, and I don't really think there were any previous values.

In that case since I don't have that Issue. Can you share your helm values?

**Comment by jiachengxu** [comment]
Here is my values.yaml
```yaml
ingress:
  enabled: false

serviceAccount:
  create: false

distributor:
  replicas: 3
  serviceMonitor:
    enable: true

ruler:
  replicas: 2
  serviceMonitor:
    enable: true

compactor:
  replicas: 3
  persistentVolume:
    enabled: true
    storageClass: gp3
    size: 50Gi
  serviceMonitor:
    enable: true

store_gateway:
  replicas: 3
  persistentVolume:
    enabled: true
    storageClass: gp3
    size: 20Gi
  serviceMonitor:
    enable: true

ingester:
  replicas: 3
  statefulSet:
    enabled: true
  persistentVolume:
    enabled: true
    storageClass: gp3
    size: 100Gi
  serviceMonitor:
    enable: true

querier:
  replicas: 3
  serviceMonitor:
    enable: true

query_frontend:
  replicas: 2
  serviceMonitor:
    enable: true

nginx:
  replicas: 3

alertmanager:
  replicas: 2
  statefulSet:
    enabled: true
  persistentVolume:
    enabled: true
    storageClass: gp3
    size: 10Gi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - alertmanager
            topologyKey: "kubernetes.io/hostname"
  serviceMonitor:
    enable: true

config:
  auth_enabled: false
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
  distributor:
    ha_tracker:
      enable_ha_tracker: true
      kvstore:
        store: consul
        consul:
          host: consul-consul-server:8500
    ring:
      kvstore:
        store: memberlist
  store_gateway:
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
  compactor:
    data_dir: /data/cortex/compactor
    compaction_interval: 30m
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
  runtime_config:
    period: "10s"
    file: "/etc/cortex-runtime-config/runtime_config.yaml"
  ruler:
    enable_alertmanager_discovery: true
    enable_api: true
    ring:
      kvstore:
        store: memberlist
  alertmanager:
    enable_api: true
    data_dir: /data/cortex/alert-data
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
  querier:
    query_store_after: 480m
    query_ingesters_within: 485m
  storage:
    engine: blocks
  blocks_storage:
    backend: s3
    bucket_store:
      bucket_index:
        enabled: true
      sync_dir: /data/tsdb-sync
      ignore_deletion_mark_delay: 1h
    s3:
      bucket_name: ...
      endpoint: ...
    tsdb:
      dir: /data/tsdb
      wal_compression_enabled: true
      retention_period: 485m
  ruler_storage:
    backend: s3
    s3:
      bucket_name: ...
      endpoint: ...
  alertmanager_storage:
    backend: s3
    s3: 
      bucket_name: ...
      endpoint: ...
  limits:
    accept_ha_samples: true
    ha_replica_label: "replica"

runtimeconfigmap:
  create: true
  runtime_config:
    overrides:
      fake:
        ...

tags:
  blocks-storage-memcached: true

memcached-blocks-metadata:
  serviceAccount:
    create: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

memcached-blocks-index:
  serviceAccount:
    create: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

memcached-blocks:
  serviceAccount:
    create: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

```

**Comment by ShuzZzle** [comment]
> Here is my values.yaml
> ......

Hmm looks pretty good. Have you checked your config in kubernetes? You should have this block configured.

```yaml
  memberlist:
    join_members:
      - "cortex-memberlist.cortex"
    bind_port: 7946
```
