### ISSUE TITLE
memcached config: no index cache backend addresses (alertmanager, compactor, distributor, query frontend)

### ISSUE THREAD

**Issue by mweibel** [cortexproject/cortex-helm-chart#299]
hi,

I upgraded to the latest helm chart version and at the same time moved from separately deployed memcached instances to the ones deployed as a subchart of the cortex helm chart (I wasn't sure initially if ArgoCD handles dependency deployments well). 

When redeploying I encountered several components which weren't able to start up with the following error message:
```
error validating config: invalid TSDB config: no index cache backend addresses
```

As a result I added `{{- include "cortex.memcached" . | nindent 12}}` to the mentioned component deployments (or statefulsets). 

I wasn't able to find a relevant change which would indicate the config validation behaviour changed between those cortex versions so I'm not sure if something is off with my deployment or if the helm chart is wrongly configured if you don't manually configured `memcached.addresses` settings. 

I'm using blocks storage. 

Cheers,
Michael

**Comment by ShuzZzle** [comment]
Hi,
> As a result I added `{{- include "cortex.memcached" . | nindent 12}}` to the mentioned component deployments (or statefulsets).

I have no idea what you mean by that? You need to the following in your values.yml to enable memcached
```yaml
tags:
  blocks-storage-memcached: true
```

Here is a guide we wrote on how to get a running starter config: https://cortexproject.github.io/cortex-helm-chart/guides/configure_memcached.html

**Comment by mweibel** [comment]
Yes, that's what I have configured. The memcacheds get deployed as they should.
The configuration of memcached backend addresses is done using [a helper](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/_helpers.tpl#L87). This helper is only included in some deployments/statefulsets (e.g. [ingester](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/ingester/ingester-statefulset.yaml#L103)) but not in e.g. [alertmanager](https://github.com/cortexproject/cortex-helm-chart/blob/master/templates/alertmanager/alertmanager-statefulset.yaml#L148). 

When alertmanager tried to start up it logged that error because the memcached backend address would not be configured. I don't think alertmanager uses it, but it seems that the validation is done regardless. 

As a result I had to add the missing calls of the `cortex.memcached` helper to the deployments/statefulsets which didn't have it yet and errored (alertmanager, compactor, distributor, query frontend). 

You don't have this error then? I do think it is weird but I don't see what could be wrong.

**Comment by mweibel** [comment]
Aha! ok now I see why the linked configuration works. Because if you do it that way, the `memcached.addresses` setting _is_ configured in the cortex configuration file.

**Comment by ShuzZzle** [comment]
> Aha! ok now I see why the linked configuration works. Because if you do it that way, the `memcached.addresses` setting _is_ configured in the cortex configuration file.

But that's interesting. I will check that alertmanager "error"

**Comment by mweibel** [comment]
so my config is:
```yaml
tags:
  # block storage memcached caching
  blocks-storage-memcached: true

# [...] stuff

    bucket_store:
      index_cache:
        backend: memcached
        memcached:
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 16777216
      chunks_cache:
        backend: memcached
        memcached:
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 33554432
      metadata_cache:
        backend: memcached
        memcached:
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 16777216

# one memcached as an example, the others are similarly configured

memcached-blocks-index:
  architecture: "high-availability"
  replicaCount: 2
  podDisruptionBudget:
    create: true
  resources:
    limits:
      memory: 1120Mi
      cpu: 1
    requests:
      memory: 256Mi
      cpu: 250m
  extraEnv:
    # -- MEMCACHED_CACHE_SIZE is the amount of memory allocated to memcached for object storage
    - name: MEMCACHED_CACHE_SIZE
      value: "1024"
    # -- MEMCACHED_MAX_CONNECTIONS is the maximum number of simultaneous connections to the memcached service
    - name: MEMCACHED_MAX_CONNECTIONS
      value: "1024"
    # -- MEMCACHED_THREADS is the number of threads to use when processing incoming requests.
    # By default, memcached is configured to use 4 concurrent threads. The threading improves the performance of
    # storing and retrieving data in the cache, using a locking system to prevent different threads overwriting or updating the same values.
    - name: MEMCACHED_THREADS
      value: "4"
  metrics:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
    serviceMonitor:
      enabled: true
```
