### ISSUE TITLE
using memcached

### ISSUE THREAD

**Issue by justinrush** [cortexproject/cortex-helm-chart#346]
We've done some general acceptance testing to solidify our understanding of the ingester/distributor tier at around 150k metrics/sec ingest and are now looking into store gateway / querier / memcached related config to make query performance acceptable when querying data outside of the range stored on the ingesters.

The default values already deploy the memcached config, but it is missing the config to actually make use of the instances (at least thats my read on the situation). When I query "old" data, I don't see any activity on the memcached instances - just watching cpu/ram in `k9s`. And the store gateway instances have these messages in them ... prior to crashing.

```
level=warn ts=2022-04-20T21:46:38.573834475Z caller=memcached_client.go:412 name=index-cache msg="failed to fetch items from memcached" numKeys=62 firstKey=P:01G0Y58N4VVZW4PBA9T5SREAXD:-OWwsy-um48KvrvhklmEkXBVDykMiLxsH0bLy63gkg4 err="memcache: connect timeout to 10.240.1.209:11211"
```

This is the values override I'm using:

```yaml
tags:
  blocks-storage-memcached: true

# this generates the overall config file that is presented to all pods
config:
  # we expect the X-Scope-OrgID to be in the headers coming from prom remote write
  # default is false, which creates a user called "fake"
  auth_enabled: true
  blocks_storage:
    bucket_store:
      sync_dir: "/data/tsdb-sync"
      index_cache:
        backend: memcached
        memcached:
          addresses: 'dns+{{ include "cortex.fullname" $ }}-memcached-blocks-index:11211'
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 16777216

      chunks_cache:
        backend: memcached
        memcached:
          addresses: 'dns+{{ include "cortex.fullname" $ }}-memcached-blocks:11211'
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 16777216

      metadata_cache:
        backend: memcached
        memcached:
          addresses: 'dns+{{ include "cortex.fullname" $ }}-memcached-blocks-metadata:11211'
          timeout: 300ms
          max_idle_connections: 750
          max_async_concurrency: 100
          max_async_buffer_size: 10000000
          max_get_multi_concurrency: 750
          max_get_multi_batch_size: 1000
          max_item_size: 16777216
      
      bucket_index:
        enabled: true
    backend: azure
    azure:
      container_name: cortex
      account_name: myacct
      account_key: mykey
    tsdb:
      dir: "/data/tsdb"
      retention_period: 6h

  ingester:
    lifecycler:
      ring:
        # since we are running on kubernetes and this isn't mission critical, 
        replication_factor: 2
    walconfig:
      wal_enabled: true
      recover_from_wal: true
      wal_dir: "/data/wal"
  querier:
    store_gateway_addresses: 'dns+{{ include "cortex.fullname" $ }}-store-gateway-headless:9095'

  # see: https://cortexmetrics.io/docs/configuration/configuration-file/#store_gateway_config
  store_gateway:
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
      replication_factor: 2

  limits:
    accept_ha_samples: true
    ha_cluster_label: __cluster__
    ha_replica_label: __replica__
    ingestion_rate: 25000
    ingestion_burst_size: 100000
    max_label_names_per_series: 42

  distributor:
  
    ring:
      kvstore:
        store: memberlist

  alertmanager_storage:
    backend: azure
    azure:
      container_name: cortex
      account_name: myacct
      account_key: mykey

ingester:
  autoscaling:
    enabled: true
    targetMemoryUtilizationPercentage: 70
    # targetCPUUtilizationPercentage: 70
    minReplicas: 1
    maxReplicas: 2
  statefulSet:
    enabled: true
  persistentVolume:
    size: 10Gi
  resources:
    requests:
      memory: 2G
      cpu: 0.02
    limits:
      memory: 2400M
      cpu: 0.4  

distributor:
  # can be removed when v > 1.4.0
  # https://github.com/cortexproject/cortex-helm-chart/commit/52f07c31f6d5dee8438ce8a66fdf02ba473e8b97
  enable: true
  autoscaling:
    enabled: true
    targetMemoryUtilizationPercentage: 80
    targetCPUUtilizationPercentage: 80
    minReplicas: 1
    maxReplicas: 3
  resources:
    requests:
      memory: 400M
      cpu: 0.4
    limits:
      memory: 500M
      cpu: 0.8  

querier:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetMemoryUtilizationPercentage: 80
  resources:
    requests:
      memory: 200M
      cpu: 0.01
    limits:
      memory: 500M
      cpu: 0.5  

query_frontend:
  replicas: 2

table_manager:
  replicas: 1

nginx:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
  image:
    repository: myregistry/nginx
    tag: 1.21
  config:
    client_max_body_size: 2M
    client_body_buffer_size: 2M

store_gateway:
  replicas: 3
  persistentVolume:
    size: 30Gi
  resources:
    requests:
      memory: 4G
      cpu: 0.1
    limits:
      memory: 6G
      cpu: 1  

compactor:
  replicas: 1
  persistentVolume:
    # We'll need to tweak the value over time as we observe how it
    # behaves. This is somewhat configurable with the compaction concurrency
    # as we need enough space to store a block and its compacted form.
    # the default is 1 so we won't expose it just now
    size: 2Gi

ruler:
  enabled: false

alertmanager:
  enabled: false

# memcached instances to deploy and use
# This is used by query-frontend for results caching
memcached-frontend:
  enabled: true
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
# used by store-gateway as shared block index cache when store-gateway scale out is enabled
memcached-blocks-index:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
memcached-blocks:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"
# used by store gateway and queriers to share metadata of fetched blocks
# reduces api calls to backend storage
memcached-blocks-metadata:
  replicaCount: 2
  extraEnv:
    - name: MEMCACHED_CACHE_SIZE
      value: "512"


```
