### ISSUE TITLE
invalid cortex.yaml config is generated with latest helm charts

### ISSUE THREAD

**Issue by mvkrishna86** [cortexproject/cortex-helm-chart#416]
Latest cortex image does not support the fields: alertnamager.storage, ruler.storage, storage.index_queries_cache_config.
But with the helm charts 1.7.0, these configs are getting generated with default values and facing the issue:

```
error loading config from /etc/cortex/cortex.yaml: Error parsing config file: yaml: unmarshal errors:
  line 5: field storage not found in type alertmanager.MultitenantAlertmanagerConfig
  line 128: field storage not found in type ruler.Config
  line 149: field index_queries_cache_config not found in type storage.Config
```

below is the part of the config I am using in the values file:

```
   config:
      alertmanager:
        enable_api: true
        external_url: /api/prom/alertmanager
        data_dir: /data/
      alertmanager_storage:
        backend: local
        local:
          path: /configs/

      ruler:
        alertmanager_url: http://cortex-alertmanager.monitoring.svc.cluster.local/api/prom/alertmanager
        enable_alertmanager_discovery: false
        enable_alertmanager_v2: false
        enable_api: true
        enable_sharding: true
        rule_path: /etc/cortex/rules
        ring:
          kvstore:
            store: memberlist
      ruler_storage:
        backend: local
        local:
          directory: /data/rules
```

Decoded secret contains the below:
```
alertmanager:
  data_dir: /data/
  enable_api: true
  external_url: /api/prom/alertmanager
  storage: {}
alertmanager_storage:
  backend: local
  local:
    path: /configs/

ruler:
  alertmanager_url: http://cortex-alertmanager.monitoring.svc.cluster.local/api/prom/alertmanager
  enable_alertmanager_discovery: false
  enable_alertmanager_v2: false
  enable_api: true
  enable_sharding: true
  ring:
    kvstore:
      store: memberlist
  rule_path: /etc/cortex/rules
  storage: {}
ruler_storage:
  backend: local
  local:
    directory: /data/rules
```
