### ISSUE TITLE
Error with usage of  Max Chunk Age

### ISSUE THREAD

**Issue by lenglet-k** [cortexproject/cortex-helm-chart#423]
Hi,

i use 2.0.0 version of cortex helm chart, wiht cortex 1.14.0.

I can't set `max_chunk_age: 2h` in `config.ingester`. When i set this parameter cortex-ingester pod are in crashloopback states with this logs:

```shell:
error loading config from /etc/cortex/cortex.yaml: Error parsing config file: yaml: unmarshal errors:
line 37: field max_chunk_age not found in type ingester.Config
```

My helm config:

```yaml

config:
  auth_enabled: true
  api:
    prometheus_http_prefix: '/prometheus'
    response_compression_enabled: true
  ingester:
    lifecycler:
      join_after: 10s
      observe_period: 10s
      final_sleep: 30s
      num_tokens: 512
      ring:
        replication_factor: 3
        kvstore:
          store: "memberlist"
    max_chunk_age: 2h

````

Or i am wrong ?
