### ISSUE TITLE
Expose ServiceMonitor labels for memcached instances and make format consistent

### ISSUE THREAD

**Issue by bljordan** [cortexproject/cortex-helm-chart#458]
Most blocks of values include a section for serviceMonitor and additionalLabels on the `ServiceMonitor`.
https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L821-L840
```
query_frontend:
  enabled: true
  replicas: 2

  service:
    annotations: {}
    labels: {}

  serviceAccount:
    # -- "" disables the individual serviceAccount and uses the global serviceAccount for that component
    name: ""

  serviceMonitor:
    enabled: false
    additionalLabels: {}
    relabelings: []
    metricRelabelings: []
    # -- Additional endpoint configuration https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#endpoint
    extraEndpointSpec: {}
    podTargetLabels: []
```

These same labels need to be exposed for all of the memcached instances.
https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L1546-L1636
```
memcached-frontend:
  # -- Enables support for caching queries in the frontend
  enabled: false
  architecture: "high-availability"
  replicaCount: 2
  resources: {}
  extraEnvVars:
    # -- MEMCACHED_CACHE_SIZE is the amount of memory allocated to memcached for object storage
    - name: MEMCACHED_CACHE_SIZE
      value: "1024"
    # -- MEMCACHED_MAX_CONNECTIONS is the maximum number of simultaneous connections to the memcached service
    - name: MEMCACHED_MAX_CONNECTIONS
      value: "1024"
    # -- MEMCACHED_THREADS is the number of threads to use when processing incoming requests.
    # By default, memcached is configured to use 4 concurrent threads. The threading improves the performance of
    # storing and retrieving data in the cache, using a locking system to prevent different threads overwriting or updating the same values.
    - name: MEMCACHED_THREADS
      value: "4"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
```

This is important because the prometheus operator picks up the ServiceMonitor resources based on a label.

Additionally, the memcached values are nested under `metrics`. This should be consistently exposed - I'd suggest placing `serviceMonitor` under each memcached instance values.

Thanks,
Ben
