### ISSUE TITLE
Default use of memberlist (ingester) and consul (distributor/ruler)?

### ISSUE THREAD

**Issue by paul-bormans** [cortexproject/cortex-helm-chart#461]
Given the cortex defaults (https://github.com/cortexproject/cortex/blob/master/docs/configuration/config-file-reference.md) and the config overrides in the chart (https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L62) you would run a cortex cluster by default using both memberlist and consul for kvstore backend.

We would like to know what the best practise is when it comes to these configurations? Are there any side-effects running these defaults?

A /config dump on one of the components tells me following:

```
distributor:
  ring:
    kvstore:
      store: consul
ruler:
  ring:
    kvstore:
      store: consul
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
```

Also if i wanted to only run memberlist, is that supported by Cortex and is there any additional config required?
