### ISSUE TITLE
Default values continue to cause alertmanager templates to be deleted

### ISSUE THREAD

**Issue by disambiguationuk** [cortexproject/cortex-helm-chart#463]
Using the following setup :
- the latest helm chart 1.15.1
- **without**  a sidecar for Alertmanager
- with Alertmanager sharded using gcp block storage
- configs and templates set by POSTing to the API

We continue to see this bug which is documented to affect using localstorage https://github.com/cortexproject/cortex/issues/4888

We've managed to resolve this by adding:
```
configs:
  alertmanager:
    data_dir: /data
```
which overrides the default ```data_dir: data/```

For reference these are our alertmanager values: 
```
  alertmanager:
    enable_api: true
    data_dir: /data
    sharding_enabled: true
    sharding_ring:
      kvstore:
        store: memberlist
    cluster:
      peer_timeout: 5s      
  alertmanager_storage:
    backend: gcs
    gcs:
      bucket_name: {{bucket-name}}
```

If this seems reasonable I'm happy to do a PR on to add that default value to path this bug

@bmaximuml @martinhale @danbrose
