### ISSUE TITLE
Version label changed even when image.tag is defined

### ISSUE THREAD

**Issue by amirulali** [cortexproject/cortex-helm-chart#519]
I wanted to configured memcached to my deployment. However, we are still running with cortex v1.17.1 while updated helm chart is using v1.18.1.

In order to separate the memcached deployment and cortex update. I've made the following changes to my values.yaml

```
image:
  repository: quay.io/cortexproject/cortex
  # -- Allows you to override the cortex version in this chart. Use at your own risk.
  tag: "v1.17.1"
  pullPolicy: IfNotPresent
```

However, when i ran `helm diff upgrade`, it's showing that the image no longer be upgraded but the label is going to change to v1.18.1

```
cortex-stg, cortex-stg, ServiceAccount (v1) has changed:
  # Source: cortex/templates/serviceaccount.yaml
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cortex-stg
    namespace: cortex-stg
    labels:
-     helm.sh/chart: cortex-2.4.0
+     helm.sh/chart: cortex-2.5.0
      app.kubernetes.io/name: cortex
      app.kubernetes.io/instance: cortex-stg
-     app.kubernetes.io/version: "v1.17.1"
+     app.kubernetes.io/version: "v1.18.1"
      app.kubernetes.io/managed-by: Helm
    annotations:
      {}
  automountServiceAccountToken: true
```

This can be solved by changing this line in `_helpers.tpl`

```
{{/*
Common labels
*/}}
{{- define "cortex.labels" -}}
helm.sh/chart: {{ include "cortex.chart" . }}
{{ include "cortex.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.tag | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
```

With above patch

```
cortex-stg, cortex-stg, ServiceAccount (v1) has changed:
  # Source: cortex/templates/serviceaccount.yaml
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cortex-stg
    namespace: cortex-stg
    labels:
-     helm.sh/chart: cortex-2.4.0
+     helm.sh/chart: cortex-2.5.0
      app.kubernetes.io/name: cortex
      app.kubernetes.io/instance: cortex-stg
      app.kubernetes.io/version: "v1.17.1"
      app.kubernetes.io/managed-by: Helm
    annotations:
      {}
  automountServiceAccountToken: true
```
