### ISSUE TITLE
values.yaml is missing chunk section inside the schema config

### ISSUE THREAD

**Issue by boseadler** [cortexproject/cortex-helm-chart#73]
The deployed resources via the helm chart are failing to start, throwing following error message:
`error validating config: invalid schema config: schema config for chunks is missing the 'prefix' setting`

It appears the values.yaml file is missing the chunk section inside the schema config [https://cortexmetrics.io/docs/chunks-storage/schema-configuration/#schema-config-example]

**Comment by rubycut** [comment]
I am trying to start cortex with block storage, and I am getting the same error.

**Comment by rubycut** [comment]
I added this to my custom.yml:

```
config:
  schema:
    configs:
      - from: "2020-11-23"
        schema: v10
        chunks:
            period: 1w
            prefix: dev_chunks_
        index:
            period: 1w
            prefix: dev_index_
        object_store: gcs
        store: bigtable-hashed   
```
Cortex now starts without problems.
