### ISSUE TITLE
Blocks engine: Ingester TSDB directory is not writable

### ISSUE THREAD

**Issue by sbaier1** [cortexproject/cortex-helm-chart#74]
Configured this chart for blocks storage engine with S3 backend and was seeing `failed to open TSDB: tsdb/fake: mkdir tsdb: read-only file system` on ingester Pods.
A short investigation led me to believe that the PodSecurityPolicy does not allow ingester to create the /tsdb dir due to `readOnlyRootFs` being set.

My workaround was adding an `emptyDir` volume to the ingester Deployment and mounting it on `/tsdb` which appears to have fixed the problem. Not sure if this is the correct way, but it's broken "out of the box" as of `0.2.0` of this chart.

**Comment by sbaier1** [comment]
For the record this can be worked around by setting these properties in the values.yaml, even with the current version:
```yaml
ingester:
  extraVolumes:
    - name: tsdb
      emptyDir: {}
  extraVolumeMounts:
    - name: tsdb
      mountPath: /tsdb
```
