### ISSUE TITLE
Centralize cloud provider specific settings in values file

### ISSUE THREAD

**Issue by gramidt** [cortexproject/cortex-helm-chart#8]
**Problem:** The chart was initially created for just AWS workloads. The values are scattered throughout the values file making it difficult to follow and make for clunky future enhancements. 

**Potential Solution:** Centralize cloud provider settings. This should also only include templates that are applicable to the selected cloud provider and settings. 

Example: 

```yaml
cloud:
  provider: aws
  aws:
    datastore:
      type: dynamodb
      dynamodb:
        ...
      s3:
        ...
    ...
  gcp:
    ...
```
