### ISSUE TITLE
No s3 endpoint in config file

### ISSUE THREAD

**Issue by terrych0u** [cortexproject/cortex-helm-chart#84]
Hi:

I'm trying to put my data to aws s3 bucket

but it always shows `no s3 endpoint in config file` this error message event I gave config in the values.yaml

here is the config :
```
  storage:
    engine: blocks
    aws:
      s3: my-testbucket
      endpoint: 's3.ap-southeast-1.amazonaws.com'
      # bucketname: 
      s3forcepathstyle: false
      access_key_id: xxxxxxxxxxxxx
      secret_access_key: xxxxxxxxxxxx
```
Is that something missing?  from the README，it's hard to know what value I should use

**Comment by MartinHell** [comment]
When using the blocks storage the s3 configuration needs to be set in the blocks_storage configuration section: https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config

So something like:

```
  blocks_storage:
    backend: s3
    s3:
      bucket_name:
```

**Comment by saikaushik-itsmyworld** [comment]
@MartinHell @terrych0u Do you have any working values.yaml file with s3 blocks_storage? I've been running into few issues setting up s3 blocks store for cortex deployment! There is not much community support on this! Appreciate if you can provide me a working values.yaml file for reference to deploy this helm chart with s3 blocks store! Thanks in advance!

**Comment by rhclaudio** [comment]
Hi All , same issue here regarding messages 
msg="error running cortex" err="no s3 endpoint in config file"

  schema:
    configs:
      s3:
      bucketnames: "testbucket"
      endpoint: "s3.us-east-1.amazonaws.com"
      s3forcepathstyle: false
      access_key_id: "#######"
      secret_access_key: "###########"

Do you have any values.yaml using s3 as object store.

Thanks in advance!!!

**Comment by terrych0u** [comment]
@saikaushik-itsmyworld 
Unfortunately, I was not able to get s3 setting properly, in the end, I switch to use Thanos.
If anyone can help with this one, I'm also very thankful

**Comment by rhclaudio** [comment]
Hi @terrych0u , what I did in order to solve this issue was that, all the metrics are being stored  in the minio container , so I am using rclone to move all of them from the container to aws S3 bucket, is not the best option but is works.

On the other hand , thanos is a very good tool as well , are you using thanos receiver for collecting metrics ? if so, could you share your values.yaml to see the receiver setup?

Thanks in advance

**Comment by terrych0u** [comment]
Hi @rhclaudio, although mino + reclone is not the best approach, still you found a way.

I'm using Thanos as my solution now, but Thanos has a well-known 2 hr data loss issue, and it also required some optimation to improve query performance. (that is why I want to use cortext.)

The Thanos helm chart is out-of-box, just put your own values to it.

If you still need some help, we can find a way to share the experiencet, not here, after all here is cortext charts :P

**Comment by rhclaudio** [comment]
Hi @terrych0u  , thanks a lot for your response, you are absolutely right ,   Terry if possible let me know how could I reach you , maybe some email?

**Comment by Xtigyro** [comment]
+1

**Comment by alfianabdi** [comment]
In my case, I just need to set the s3 endpoint to make error disappear

```
blocks_storage: 
  backend: s3
  s3:
    bucket_name: mybucket
    endpoint: s3.ap-southeast-1.amazonaws.com
```

**Comment by arpitjindal97** [comment]
In case if anyone still stumbles upon this issue. Here is the config that works:

```
config:
  storage:
    engine: blocks
  blocks_storage:
    backend: s3
    s3:
      bucket_name: xxx
      endpoint: s3.eu-west-1.amazonaws.com
      access_key_id: xxx
      secret_access_key: xxx
      insecure: true
```

For some reason, adding region field was giving error. So, I removed it

**Comment by jnsrikanth** [comment]
What about using Azure Storage for the blocks configuration in the Helm chart? Can I configure azure as the backend storage instead of S3?

**Comment by benjyiw** [comment]
I ran into this issue today and hit my head against the wall for a few hours. So here are the things that I have learned that might help someone else in the future.

The error `no s3 endpoint in config file` can happen for multiple components. So far, this issue only touches on the `blocks_storage` key in the config. Take note of what that component is that is throwing the error and provide it's corresponding backend config. In my case, I was getting the error on the `ruler` component, so I added a `ruler_storage` configuration block with additional s3 configuration. Same thing with alertmanager.

```yaml
config:
  storage:
    engine: blocks
  blocks_storage:
    backend: s3
    s3:
      bucket_name: <omitted>
      endpoint: s3.us-east-1.amazonaws.com
      access_key_id: <omitted>
      secret_access_key: <omitted>
  ruler_storage:
    backend: s3
    s3:
      bucket_name: <omitted>
      endpoint: s3.us-east-1.amazonaws.com
      access_key_id: <omitted>
      secret_access_key: <omitted>
  alertmanager_storage:
    backend: s3
    s3: 
      bucket_name: <omitted>
      endpoint: s3.us-east-1.amazonaws.com
      access_key_id: <omitted>
      secret_access_key: <omitted>
```

**Comment by n1nj4-r4cc00n** [comment]
In case someone else is looking into gcp configuration, you have to specify the backend for the block_storage even if you did in the common section. So on your custom.yaml values file
`mimir:
  structuredConfig:
    common:
      storage:
        backend: gcs
    blocks_storage:
      backend: gcs
      gcs:
        bucket_name: your_bucket_name`

**Comment by ksingh-scogo** [comment]
@n1nj4-r4cc00n  You are my hero 

For community members those who are facing problems configuring Azure Blob with Mimir , use the below config, it worked

```
  structuredConfig:
    common:
      storage:
        backend: azure
        azure:
          account_key: "<YOUR KEY HERE>"
          account_name: <ACKT_NAME>
          endpoint_suffix: "blob.core.windows.net"
    blocks_storage:
      backend: azure ## This line is important here, official docs are missing this
      azure:
        container_name: mimir-dev-blocks
    alertmanager_storage:
      backend: azure ## This line is important here, official docs are missing this
      azure:
        container_name: mimir-dev-alertmanager
    ruler_storage:
      backend: azure ## This line is important here, official docs are missing this
      azure:
        container_name: mimir-dev-ruler
```
