### ISSUE TITLE
Using Azure blob storage - multiple services say "no s3 endpoint in config file"

### ISSUE THREAD

**Issue by junkiebev** [cortexproject/cortex-helm-chart#97]
I'm attempting to use Azure Blob Storage for a deployment - using this config:
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cortex.dev.foo.com
      paths:
        - /
  tls: []
config:
  ingester:
    lifecycler:
      ring:
        kvstore:
          consul:
            host: "cortex-consul.cortex:8500"
  schema:
     configs: []
  storage:
    engine: blocks
    azure:
      container_name: cortex
      account_name: mystorageaccount
      account_key: REDACTED
```

It's apparently using s3 by default, and I don't see anywhere to alter that

**Comment by khaines** [comment]
The blocks specific settings for storage go under the `blocks_storage` object in the YAML configuration. You've set the azure settings under `storage`. 

Here are the specifics for  that configuration section: https://cortexmetrics.io/docs/configuration/configuration-file/#blocks_storage_config

Note, you must set the backend to `azure`, as it does default to s3

**Comment by junkiebev** [comment]
Got it. Do I need Cassandra if I'm using blocks?

**Comment by MartinHell** [comment]
Are these bucket settings only relevant for chunks storage? https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L89-L118

If blocks storage should only be configured in "blocks_storage_config" section then maybe a comment in the values.yaml saying this could help?

**Comment by saidben7243** [comment]
@junkiebev  and I are working on the same config.  We are seeing this new error thrown by the querier container
`error running cortex" err="failed to initialize querier for engine 'blocks': no store-gateway address configured`

These are the code blocks of querier and store_gateway, can you please advise what are we missing?

`ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cortex.dev.foo.com
      paths:
        - /
  tls: []
config:
  ingester:
    lifecycler:
      ring:
        kvstore:
          consul:
            host: cortex-consul.cortex:8500
  schema:
     configs: []
  storage:
    engine: blocks
    azure:
      container_name: cortex
      account_name: mystorageacc
      account_key: REDACTED
    cassandra:
      addresses: cortex-cassandra.cortex
      keyspace: cortex # configure desired keyspace here.
      auth: true
      username: myusername
      password: REDACTED
  blocks_storage:
    backend: azure
    azure:
      container_name: cortex
      account_name: mystorageacc
      account_key: REDACTED
querier:
  store_gateway_addresses: store-gateway-1:9008,store-gateway-2:9009
store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: consul
      consul:
        host: cortex-consul.cortex:8500`

**Comment by saidben7243** [comment]
@junkiebev and I are working on the same config. We are seeing this new error now thrown by the querier container
`failed to initialize querier for engine 'blocks': no store-gateway address configured`

This is our config file, can you please advise what are we missing?

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cortex.dev.foo.com
      paths:
        - /
  tls: []
config:
  ingester:
    lifecycler:
      ring:
        kvstore:
          consul:
            host: cortex-consul.cortex:8500
  schema:
     configs: []
  storage:
    engine: blocks
    azure:
      container_name: cortex
      account_name: mystorageacc
      account_key: REDACTED
    cassandra:
      addresses: cortex-cassandra.cortex
      keyspace: cortex # configure desired keyspace here.
      auth: true
      username: myusername
      password: REDACTED
  blocks_storage:
    backend: azure
    azure:
      container_name: cortex
      account_name: mystorageacc
      account_key: REDACTED
querier:
  # Used when the blocks sharding is disabled.
  store_gateway_addresses: store-gateway-1:9008,store-gateway-2:9009
store_gateway:
  sharding_enabled: true
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: consul
      consul:
        host: cortex-consul.cortex:8500
```

**Comment by saidben7243** [comment]
It looks like we need to set up the store gateway addresses in the blocks storage config, can you advise how that could be done? 

I did disable sharding in the store_gateway:
```yaml
store_gateway:
  sharding_enabled: false
```

**Comment by khaines** [comment]
Your querier indentation is incorrect, at least in this snippet above. It needs to be a child of config, not a sibling. `config.querier.store_gateway_addresses` is what needs to be set and you have defined `querier.store_gateway_addresses`

 Unfortunately, there is a querier object outside of config as well, but that relates to the querier deployment resources, not the cortex config settings of the querier.

**Comment by junkiebev** [comment]
I think I'm almost there - everything launches except for the alert manager sts, which complains that 

```log
evel=info ts=2021-01-06T03:47:37.410539691Z caller=main.go:178 msg="Starting Cortex" version="(version=1.4.0, branch=HEAD, revision=23554ce02)"
level=info ts=2021-01-06T03:47:37.411367601Z caller=server.go:225 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2021-01-06T03:47:37.412653517Z caller=cluster.go:154 component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
level=error ts=2021-01-06T03:47:37.414066734Z caller=log.go:149 msg="error running cortex" err="Failed to get final advertise address: No private IP address found, and explicit IP not provided\ncreate 
```

My answers.yaml:
```yaml
store_gateway:
  replicas: 1
  extraArgs:
    log.level: debug
alertmanager:
  replicas: 1
  statefulSet:
    enabled: true
tags:
  blocks-storage-memcached: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cortex.dev.corp.foo.com
      paths:
        - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
config:
  ingester:
    lifecycler:
      ring:
        kvstore:
          consul:
            host: "cortex-consul.cortex:8500"
  schema:
     configs: []
  storage:
    engine: blocks
    azure:
      container_name: cortex
      account_name: cortexmetricsnp
      account_key: REDACTED
    cassandra:
      addresses: cortex-cassandra.cortex
      keyspace: cortex # configure desired keyspace here.
      auth: true
      username: root
      password: REDACTED
  blocks_storage:
    backend: azure
    azure:
      container_name: cortex
      account_name: cortexmetricsnp
      account_key: REDACTED
  querier:
    # Used when the blocks sharding is disabled.
    store_gateway_addresses: "cortex-store-gateway-headless:9095"
memcached:
  enabled: true
memcached-index-read:
  enabled: true
memcached-index-write:
  enabled: true
memcached-frontend:
  enabled: true
```

1) I'm presuming that I need to specify a `config.alertmanager.cluster_bind_address` or `config.alertmanager.cluster_advertise_address`, but it's not apparent from the services what those should be (or if they need to be set with a reference to the downstream api value for pod IP?)
2) Should I also specify a `config.alertmanager.external_url`? If so, would the value be `http://cortex.dev.corp.foo.com/api/prom/alertmanager`?
3) Does this yaml block need to be present in both `config.storage` and `config.blocks_storage`, or is one sufficient?
```yaml
    azure:
      container_name: cortex
      account_name: cortexmetricsnp
      account_key: REDACTED
```

Thanks again for all the help!

**Comment by junkiebev** [comment]
I tried this using the `config.expand-env` setting, but it still doesn't seem to like the config:

```yaml
alertmanager:
  replicas: 1
  statefulSet:
    enabled: true
  extraArgs:
    log.level: debug
    config.expand-env: "true"
  env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: alertmanager_cluster_advertise_address
    value: "$(POD_IP):9095"
  - name: alertmanager.cluster_advertise_address
    value: "$(POD_IP):9095"
  - name: config_alertmanager_cluster_advertise_address
    value: "$(POD_IP):9095"
  - name: config.alertmanager_cluster_advertise_address
    value: "$(POD_IP):9095"
  - name: config.alertmanager.cluster_advertise_address
    value: "$(POD_IP):9095"
  - name: cluster_advertise_address
    value: "$(POD_IP):9095"
```

I'm somewhat at a loss and the documentation around using that feature is not incredibly clear

**Comment by saidben7243** [comment]
Would you be so kind to let us know how can we resolve this error please?

`"couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"`

@junkiebev already provided the details above.

**Comment by gburton1** [comment]
@junkiebev could you post your final values.yaml that you got working? That would be super-helpful for others trying to get Cortex with blocks storage working on Azure using this Helm chart (like me!). There isn't much documentation out there, so this ticket has been a helpful source of info.

**Comment by junkiebev** [comment]
@gburton1 you bet. This is what I'm running r/n and everything is up other than alertmanager

```yaml
store_gateway:
  replicas: 1
  extraArgs:
    log.level: debug
alertmanager:
  cluster:
    advertise-address: "0.0.0.0:9094"
  replicas: 1
  statefulSet:
    enabled: true
  extraArgs:
    log.level: debug
    config.expand-env: "true"
  
tags:
  blocks-storage-memcached: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cortex.dev.corp.company.com
      paths:
        - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
config:
  alertmanager:
    external_url: /api/prom/alertmanager
  api:
    prometheus_http_prefix: /prometheus
  auth_enabled: false
  blocks_storage:
    backend: azure
    tsdb:
      dir: /data/tsdb
    bucket_store:
      sync_dir: /data/tsdb-sync
    azure:
      account_key: REDACTED
      account_name: REDACTED
      container_name: REDACTED
  chunk_store:
    chunk_cache_config:
      memcached:
        expiration: 1h
      memcached_client:
        timeout: 1s
    max_look_back_period: 0s
  distributor:
    pool:
      health_check_ingesters: true
    shard_by_all_labels: true
  frontend:
    compress_responses: true
    log_queries_longer_than: 10s
  ingester:
    lifecycler:
      final_sleep: 0s
      join_after: 0s
      num_tokens: 512
      ring:
        kvstore:
          consul:
            consistent_reads: true
            host: cortex-consul:8500
            http_client_timeout: 20s
          prefix: collectors/
          store: consul
        replication_factor: 3
    max_transfer_retries: 0
  ingester_client:
    grpc_client_config:
      max_recv_msg_size: 104857600
      max_send_msg_size: 104857600
  limits:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  memberlist:
    join_members: []
  querier:
    active_query_tracker_dir: /data/cortex/querier
    query_ingesters_within: 12h
    store_gateway_addresses: cortex-store-gateway-headless:9095
  query_range:
    align_queries_with_step: true
    cache_results: true
    results_cache:
      cache:
        memcached:
          expiration: 1h
        memcached_client:
          timeout: 1s
    split_queries_by_interval: 24h
  ruler:
    enable_alertmanager_discovery: false
  schema:
    configs: []
  server:
    grpc_listen_port: 9095
    grpc_server_max_concurrent_streams: 1000
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    http_listen_port: 8080
  storage:
    engine: blocks
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
memcached:
  enabled: true
memcached-index-read:
  enabled: true
memcached-index-write:
  enabled: true
memcached-frontend:
  enabled: true
```
